export const WHITE = "grey lighten-5";
export const PRIMARY_BLUE = "deep-purple accent-3"; //#651fff
export const PRIMARY_RED = "deep-orange accent-4"; // #dd2c00 
export const GRAPH_BACKGROUND = "blue-grey darken-1";
export const PROFILE_BACKGROUND = "grey lighten-1";
export const MENU_BACKGROUND = "grey darken-1"; // #757575 grey darken-1
export const DEFAULT_BUTTON = "cyan darken-1"; //
export const SELECTED_BUTTON = "green accent-3"; //#00e676 
export const SELECTED_BACKGROUND = "green accent-1";
export const NEXT_BUTTON = "teal"; // #dd2c00 
export const BACK_BUTTON = "yellow darken-3";
export const AUTOFILL_BUTTON = "yellow"; // #dd2c00 
export const TITLE1 = "yellow-text text-lighten-5"; // #fffde7 yellow lighten-5
export const TITLE2 = "lime-text text-darken-4"; // #827717
export const TEXT1 = "amber-text text-accent-1"; // #ffd740
export const TEXT2 = "deep-orange-text text-darken-4";
export const TEXT3 = "teal-text text-darken-4"; // #004d40
export const TEXT4 = "blue-grey-text text-darken-1";
export const ACCENT1 = "pink lighten-5";
export const ACCENT2 = "red lighten-4";