export const WHITE = "grey lighten-5";
export const PRIMARY = "deep-purple accent-3"; //#4527a0
export const SECONDARY = "blue-grey darken-1";
export const TERTIARY = "grey lighten-1";
export const MENU = "grey darken-1"; // #757575 grey darken-1
export const SELECTED = "green accent-1";
export const TITLE = "yellow-text text-lighten-5"; // #fffde7 yellow lighten-5
export const TITLE2 = "lime-text text-darken-4"; // #827717
export const TEXT = "amber-text text-accent-2"; // #ffd740
export const TEXT2 = "deep-orange-text text-darken-4";
export const TEXT3 = "teal-text text-darken-4"; // #004d40
export const TEXT4 = "blue-grey-text text-darken-1";
export const ACCENT1 = "pink lighten-5";
export const ACCENT2 = "red lighten-4";
export const ACCENT3 = "green accent-3"; //#00e676 
export const ACCENT4 = "cyan darken-1"; //
export const ACCENT5 = "deep-orange accent-4"; // #dd2c00 
